# Generated by Django 4.2.1 on 2023-06-03 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(1, 'the field must contain at least 1 characters')])),
            ],
        ),
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5, 'the field must contain at least 5 characters')])),
                ('description', models.CharField(max_length=1000, validators=[django.core.validators.MinLengthValidator(10, 'the field must contain at least 10 characters')])),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('O', 'Open'), ('W', 'Working'), ('D', 'Done'), ('v', 'Overdue')], default='O', max_length=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(to='todo.tag')),
            ],
        ),
    ]
