# Generated by Django 4.2.1 on 2023-06-03 19:08

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='due_date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date.today)]),
        ),
    ]
