# Generated by Django 4.2.1 on 2023-06-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_todomodel_id_todomodel_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
