# Generated by Django 4.2.1 on 2023-06-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todomodel_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodel',
            name='uid',
        ),
        migrations.AddField(
            model_name='todomodel',
            name='id',
            field=models.AutoField(default=3, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
